name: build

# Triggers the workflow on pull request events but only for the master
# branch
on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run linter
      run: poetry run black bootstrap_stat/ tests/
    - name: Run test cases
      run: poetry run python -m pytest
